; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git ;platformio/espressif32@^6.1.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = 8MB_20-20-40.csv
extra_scripts = genCRC-auto.py
;edit to suit your board via: https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=0
;	-DCORE_DEBUG_LEVEL=5
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps = 
	bblanchon/StreamUtils@^1.8.0
	fastled/FastLED@3.7.8
;	fastled/FastLED@^3.9.13
	bblanchon/ArduinoJson@^7.0.4
	sparkfun/SparkFun LSM6DS3 Breakout@^1.0.3
	olikraus/U8g2@^2.35.19
	h2zero/NimBLE-Arduino@^2.2.1
;	h2zero/NimBLE-Arduino@^1.4.3
	adafruit/Adafruit BusIO@^1.16.1
	frankboesing/FastCRC@^1.41
	majicdesigns/MD_MAX72XX@^3.5.1
	arduinogetstarted/ezButton@^1.0.4
	ESP32Async/AsyncTCP@^3.3.5
	ESP32Async/ESPAsyncWebServer@^3.7.0
	ayushsharma82/ElegantOTA@^3.1.5

[env:esp32dev] ;normally 4MB, no PSRAM (need to solder one), will get nuked in future
platform = https://github.com/pioarduino/platform-espressif32.git ;platformio/espressif32@^6.1.0
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = 4MB_17-17-05.csv
extra_scripts = genCRC-auto.py
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
;	-DCORE_DEBUG_LEVEL=5
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps = 
	bblanchon/StreamUtils@^1.8.0
	fastled/FastLED@3.7.8
;	fastled/FastLED@^3.9.13
	bblanchon/ArduinoJson@^7.0.4
	sparkfun/SparkFun LSM6DS3 Breakout@^1.0.3
	olikraus/U8g2@^2.35.19
	h2zero/NimBLE-Arduino@^2.2.1
;	h2zero/NimBLE-Arduino@^1.4.3
	adafruit/Adafruit BusIO@^1.16.1
	frankboesing/FastCRC@^1.41
	majicdesigns/MD_MAX72XX@^3.5.1
	arduinogetstarted/ezButton@^1.0.4
	ESP32Async/AsyncTCP@^3.3.5
	ESP32Async/ESPAsyncWebServer@^3.7.0
	ayushsharma82/ElegantOTA@^3.1.5
