[env:esp32-s3]
;board = esp32-s3-devkitc1-n16r8 ;Depending on your board, change the "n16r8" to your board! Example: esp32-s3-devkitc1-n8r2
;On 21.3.25, with "4d_systems_esp32s3_gen4_r8n16", "https://github.com/pioarduino/platform-espressif32.git#develop" this code compiles and doesn't crashloop
;Need to test new added fucntions and new update libraries,publish animator, and try to make it available with other boards, N16R8 only atm
board = 4d_systems_esp32s3_gen4_r8n16
platform = https://github.com/pioarduino/platform-espressif32.git#develop
framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_build.partitions = 8MB_20-20-40.csv ;If your ESP has 4MB of Flash, have this to "4MB_17-17-05.csv"
extra_scripts = genCRC-auto.py
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=0
;	-DCORE_DEBUG_LEVEL=5
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps = 
	bblanchon/StreamUtils@1.8.0
	fastled/FastLED@3.7.8
;	fastled/FastLED@^3.9.13
;	https://github.com/FastLED/FastLED.git
	bblanchon/ArduinoJson@7.0.4
	sparkfun/SparkFun LSM6DS3 Breakout@1.0.3
	olikraus/U8g2@2.35.19
	h2zero/NimBLE-Arduino@2.2.1
	adafruit/Adafruit BusIO@1.16.1
	frankboesing/FastCRC@1.41
	majicdesigns/MD_MAX72XX@3.5.1
	arduinogetstarted/ezButton@1.0.4
	ESP32Async/AsyncTCP@3.3.6 ;3.3.7 doesn't compile
	ESP32Async/ESPAsyncWebServer@3.7.2 ;3.7.3 doesn't compile
	ayushsharma82/ElegantOTA@3.1.5