[env:esp32-s3]
board = esp32-s3-devkitc1-n16r8 ;Depending on your board, change the "n16r8" to your board! Example: esp32-s3-devkitc1-n8r2
board_build.variant = esp32_s3r8n16 ;rmt conflict fix, "esp32s3" variant imports soc_caps.h at that does some RMT define things... 
;platform = https://github.com/pioarduino/platform-espressif32.git#develop
platform = https://github.com/pioarduino/platform-espressif32.git
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_build.partitions = 4MB_17-17-05.csv
extra_scripts = genCRC-auto.py
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=0
;	-DCORE_DEBUG_LEVEL=5
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
;	-DARDUINO_USB_CDC_ON_BOOT=1 ;If using ESP with only one USB port, uncomment this for working monitor/console
lib_deps = 
	bblanchon/StreamUtils@1.9.0
	fastled/FastLED@3.7.8
;	fastled/FastLED@^3.9.20
;	https://github.com/FastLED/FastLED.git
	bblanchon/ArduinoJson@7.4.3
	sparkfun/SparkFun LSM6DS3 Breakout@1.0.3
	olikraus/U8g2@2.36.5
	h2zero/NimBLE-Arduino@2.5.0
	adafruit/Adafruit BusIO@1.17.4
	https://github.com/FrankBoesing/FastCRC.git
	majicdesigns/MD_MAX72XX@3.5.1
	arduinogetstarted/ezButton@1.0.6
	ESP32Async/AsyncTCP@3.4.10
	ESP32Async/ESPAsyncWebServer@3.10.3
	ayushsharma82/ElegantOTA@3.1.7
	adafruit/Adafruit VL53L1X@3.1.2